Load CIFAR-10 Dataset

In [ ]:
!pip install tensorflow

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

170498071/170498071 [==============================] - 22s 0us/step


Split

In [ ]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Extract the cat and dog images and labels
D1 = [(x_train[i], y_train[i]) for i in range(len(x_train)) if y_train[i] == 3]
D2 = [(x_train[i], y_train[i]) for i in range(len(x_train)) if y_train[i] == 5]

# Extract the training and testing images and labels
Trd1 = D1[:4000]
Trd2 = D2[:5000]

Tsd1 = D1[4000:]
Tsd2 = D2[5000:]

# Extract the image and label arrays
img_Trd1 = np.array([x for x, _ in Trd1])
img_Trd2 = np.array([x for x, _ in Trd2])

img_Tsd1 = np.array([x for x, _ in Tsd1])
img_Tsd2 = np.array([x for x, _ in Tsd2])

lb1_Trd1 = np.array([y for _, y in Trd1])
lb2_Trd2 = np.array([y for _, y in Trd2])

lb1_Tsd1 = np.array([y for _, y in Tsd1])
lb2_Tsd2 = np.array([y for _, y in Tsd2])

# Now you can use the extracted data in your code

In [ ]:
# Extract individual images and labels from D1 and D2
x1, y1 = D1[0]
x_n, y_n = D1[-1]
x_m, y_m = D2[-1]

# Use the extracted variables in the subsequent code
D1 = [(x, y) for x, y in D1]
D2 = [(x, y) for x, y in D2]

Trd1 = [(x, y) for x, y in D1[:4000]]
Trd2 = [(x, y) for x, y in D2[:5000]]

Tsd1 = [(x, y) for x, y in D1[4000:]]
Tsd2 = [(x, y) for x, y in D2[5000:]]

# Extract the image and label arrays
img_Trd1 = np.array([x for x, _ in Trd1])
img_Trd2 = np.array([x for x, _ in Trd2])

img_Tsd1 = np.array([x for x, _ in Tsd1])
img_Tsd2 = np.array([x for x, _ in Tsd2])

lb1_Trd1 = np.array([y for _, y in Trd1])
lb2_Trd2 = np.array([y for _, y in Trd2])

lb1_Tsd1

array([[3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
       [3],
    

In [ ]:
print(y_train[:10])

[[6]
 [9]
 [9]
 [4]
 [1]
 [1]
 [2]
 [7]
 [8]
 [3]]


In [ ]:
print(x_train[:10])

[[[[ 59  62  63]
   [ 43  46  45]
   [ 50  48  43]
   ...
   [158 132 108]
   [152 125 102]
   [148 124 103]]

  [[ 16  20  20]
   [  0   0   0]
   [ 18   8   0]
   ...
   [123  88  55]
   [119  83  50]
   [122  87  57]]

  [[ 25  24  21]
   [ 16   7   0]
   [ 49  27   8]
   ...
   [118  84  50]
   [120  84  50]
   [109  73  42]]

  ...

  [[208 170  96]
   [201 153  34]
   [198 161  26]
   ...
   [160 133  70]
   [ 56  31   7]
   [ 53  34  20]]

  [[180 139  96]
   [173 123  42]
   [186 144  30]
   ...
   [184 148  94]
   [ 97  62  34]
   [ 83  53  34]]

  [[177 144 116]
   [168 129  94]
   [179 142  87]
   ...
   [216 184 140]
   [151 118  84]
   [123  92  72]]]


 [[[154 177 187]
   [126 137 136]
   [105 104  95]
   ...
   [ 91  95  71]
   [ 87  90  71]
   [ 79  81  70]]

  [[140 160 169]
   [145 153 154]
   [125 125 118]
   ...
   [ 96  99  78]
   [ 77  80  62]
   [ 71  73  61]]

  [[140 155 164]
   [139 146 149]
   [115 115 112]
   ...
   [ 79  82  64]
   [ 68  70  55]
   [ 67  69

In [ ]:
D1 = [(x1, y1), ..., (x_n,y_n)]  # cat set | 5000
D2 = [(x1, y1), ..., (x_m, y_m)]  # dog set | 6000

Trd1 = [(x1, y1), ..., (x_n - 1000, y_n - 1000)]  # training cat set | 4000
Trd2 = [(x1, y1), ..., (x_m - 1000, y_m - 1000)]  # training dog set | 5000

Tsd1 = [(x_n - 1000, y_n - 1000), ..., (x_n, y_n)]  # testing cat set | 1000
Tsd2 = [(x_n - 1000, y_n - 1000), ..., (x_n, y_n)]  # testing dog set | 1000

img_Trd1 = [x1, ..., x_n-1000] # training cat image set
img_Trd2 = [x1, ..., x_m-1000] # training dog image set

img_Tsd1 = [x_n-1000, ..., x_n] # testing cat image set
img_Tsd2 = [x_m-1000, ..., x_m] # testing dog image set

lb1_Trd1 = [y1, ..., y_n-1000] # training cat label set
lb2_Trd2 = [y1, ..., y_m-1000] # training dog label set

lb1_Tsd1 = [y_n-1000, ..., y_n] # testing cat label set
lb2_Tsd2 = [y_m-1000, ..., y_m] # testing dog label set

a1 = 4000
b1 = 5000

for i in range(10):
    na1 = a1
    nb1 = int(((100-i*10)/160)*b1)

print('number of images from D1:', na1)
print('number of images from D2:', nb1)
print('number of deducted images from D2 at',i, 'th training:', b1-nb1)

number of images from D1: 4000
number of images from D2: 312
number of deducted images from D2 at 9 th training: 4688
